version: "3.5"

services:
  php:
    build: .
    tty: true
    links:
      -   mysql
    volumes:
      - ./:/app:cached

  mysql:
    image: mariadb
    restart: always
    volumes:
      - ./.data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=database
    ports:
      - 3306:3306